AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'external/**/*'

# There is a difference in line endings between
# GitHub Actions and Bazel CI.
# https://github.com/bazel-contrib/rules_ruby/issues/27
Layout/EndOfLine:
  Enabled: false
