# frozen_string_literal: true

source 'https://rubygems.org'
gemspec

gem 'debug', '>= 1.0.0', platforms: %i[mri mswin64]
# Gem with native extensions.
# Use 5.0.1 to test for Jars fetching on JRuby.
# https://github.com/bazel-contrib/rules_ruby/issues/218
gem 'psych', '5.0.1'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.64'
