# frozen_string_literal: true

source 'https://rubygems.org'
gemspec

gem 'debug', '>= 1.0.0', platforms: %i[mri mswin64]
gem 'psych', '~> 5.3' # native extensions
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.64'
