local_repository(
    name = "rules_ruby",
    path = "../..",
)

load("@rules_ruby//ruby:deps.bzl", "rb_bundle", "rb_register_toolchains")
load("ruby_version.bzl", "RUBY_VERSION")

rb_register_toolchains(
    version = RUBY_VERSION,
)

rb_bundle(
    name = "bundle",
    srcs = [
        "//:Gemfile.lock",
        "//:gem.gemspec",
        "//:lib/gem/version.rb",
    ],
    env = {
        "BUNDLE_BUILD__FOO": "bar",
    },
    gemfile = "//:Gemfile",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
    ],
)
