# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("native_ext.gemspec")

Rake::ExtensionTask.new("native_ext", GEMSPEC) do |ext|
  ext.lib_dir = "lib/native_ext"
end

task default: %i[clobber compile]
