load(":jars_downloader_tests.bzl", "jars_downloader_test_suite")
load(":toolchain_selection_tests.bzl", "toolchain_selection_test_suite")
load(":utils_tests.bzl", "utils_test_suite")

jars_downloader_test_suite()

utils_test_suite()

toolchain_selection_test_suite()
