load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "default_gems",
    srcs = ["default_gems.bzl"],
    visibility = ["//ruby:__subpackages__"],
)

bzl_library(
    name = "gemfile_lock_parser",
    srcs = ["gemfile_lock_parser.bzl"],
    visibility = ["//ruby:__subpackages__"],
)

bzl_library(
    name = "jars_downloader",
    srcs = ["jars_downloader.bzl"],
    visibility = ["//ruby:__subpackages__"],
)
