"""@generated by @rules_ruby//:ruby/private/bundle_fetch.bzl"""

load("@rules_ruby//ruby:defs.bzl", "rb_bundle_install", "rb_gem", "rb_gem_install", "rb_git_gem")

package(default_visibility = ["//visibility:public"])

rb_bundle_install(
    name = "{name}",
    srcs = {srcs},
    env = {env},
    gemfile = "{gemfile_path}",
    gemfile_lock = "{gemfile_lock_path}",
    gems = {gems},
    git_gem_srcs = {git_gem_srcs},
    ruby = {ruby},
)

{gem_fragments}

{gem_install_fragments}

# vim: ft=bzl
