source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2", ">= 8.0.2.1"

# Pin minitest to 5.x - minitest 6.x has breaking API changes incompatible with Rails 8.0.x
gem "minitest", "~> 5.25"

# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]
gem "tailwindcss-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end

gem "cancancan", "~> 3.6"

gem "devise", "~> 4.9"

# Pin default gems with C extensions to versions bundled with rv-ruby Ruby
# binaries. The list can be found at https://stdgems.org/<ruby-version> (e.g,
# https://stdgems.org/3.4.8 for Ruby 3.4.8).  These gems should NOT be
# downloaded - they're pre-compiled in rv-ruby with portable dependencies.
#
# IMPORTANT: These gems must be listed in the excluded_gems list in the
# bundle_fetch configured in your MODULE.bazel file.
gem "date", "3.4.1"
gem "digest", "3.2.0"
gem "etc", "1.4.6"
gem "fcntl", "1.2.0"
gem "fiddle", "1.1.6"
gem "io-console", "0.8.1"
gem "io-nonblock", "0.3.2"
gem "io-wait", "0.3.2"
gem "json", "2.9.1"
gem "openssl", "3.3.1"
gem "pathname", "0.4.0"
gem "prism", "1.5.2"
gem "psych", "5.3.1"
gem "stringio", "3.1.2"
gem "strscan", "3.1.2"
gem "zlib", "3.2.1"
